version: '3.3'

volumes:
  mongo:
    driver: local
  node_modules:
    driver: local

services:
  app:
    command: npm test
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  # app-test:
  #   command: test
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:3.4.4
    ports:
      - "27017"
    volumes:
      - mongo:/data
